import type { KundenRecord } from '@/lib/kunden/types';

const kundenRecords: KundenRecord[] = [
  {
    id: 'k-1001',
    number: 'KND-2026-1001',
    name: 'Wohnpark Isar GmbH',
    branche: 'Wohnungswirtschaft',
    segment: 'A',
    status: 'AKTIV',
    owner: 'Lea Winter',
    score: 88,
    consentState: 'ERTEILT',
    retentionClass: 'VERTRAG',
    region: 'Muenchen',
    nextFollowUpAt: '2026-03-15T09:00:00.000Z',
    createdAt: '2025-11-12T08:00:00.000Z',
    updatedAt: '2026-03-10T14:20:00.000Z',
    objekte: [
      {
        id: 'o-5001',
        kundenId: 'k-1001',
        name: 'Wohnpark Isar - Haus A',
        objektTyp: 'Wohnanlage',
        adresse: 'Isarstrasse 12, 80331 Muenchen',
        region: 'Muenchen',
        serviceIntervalDays: 90,
        zugangshinweise: 'Schluessel ueber Hausverwaltung',
        riskClass: 'LOW',
        status: 'AKTIV',
      },
      {
        id: 'o-5002',
        kundenId: 'k-1001',
        name: 'Wohnpark Isar - Tiefgarage',
        objektTyp: 'Wohnanlage',
        adresse: 'Isarstrasse 14, 80331 Muenchen',
        region: 'Muenchen',
        serviceIntervalDays: 120,
        riskClass: 'MEDIUM',
        status: 'PLANBAR',
      },
    ],
    ansprechpartner: [
      {
        id: 'c-9001',
        kundenId: 'k-1001',
        objektIds: ['o-5001', 'o-5002'],
        name: 'Anna Krueger',
        rolle: 'Objektleitung',
        email: 'anna.krueger@wohnpark-isar.de',
        telefon: '+49 89 111100',
        bevorzugterKanal: 'email',
        dsgvoConsent: 'ERTEILT',
        status: 'PRIMAER',
        primary: true,
        lastContactAt: '2026-03-08T13:00:00.000Z',
      },
      {
        id: 'c-9002',
        kundenId: 'k-1001',
        objektIds: ['o-5001'],
        name: 'Martin Abel',
        rolle: 'Buchhaltung',
        email: 'buchhaltung@wohnpark-isar.de',
        telefon: '+49 89 111199',
        bevorzugterKanal: 'email',
        dsgvoConsent: 'ERTEILT',
        status: 'VALIDIERT',
        primary: false,
      },
    ],
    reminders: [
      {
        id: 'r-7001',
        scope: 'KUNDE',
        targetId: 'k-1001',
        title: 'Q2 Rahmenvertrag pruefen',
        priority: 'MEDIUM',
        startAt: '2026-03-01T08:00:00.000Z',
        dueAt: '2026-03-20T18:00:00.000Z',
        pauseWindows: [],
        breachState: 'ON_TRACK',
      },
    ],
    activities: [
      {
        id: 'a-3001',
        entityType: 'KUNDE',
        entityId: 'k-1001',
        type: 'FOLLOW_UP',
        title: 'Folgeauftrag fuer Treppenhaus angefragt',
        payload: 'Angebot in KW12 vorbereiten',
        createdBy: 'Lea Winter',
        createdAt: '2026-03-08T13:05:00.000Z',
        visibility: 'internal',
      },
    ],
    duplicateCandidates: [],
  },
  {
    id: 'k-1002',
    number: 'KND-2026-1002',
    name: 'Baukontor Rosenheim AG',
    branche: 'Gewerbe',
    segment: 'B',
    status: 'LEAD',
    owner: 'Jan Klose',
    score: 63,
    consentState: 'UNBEKANNT',
    retentionClass: 'STANDARD',
    region: 'Rosenheim',
    nextFollowUpAt: '2026-03-13T10:00:00.000Z',
    createdAt: '2026-02-20T09:00:00.000Z',
    updatedAt: '2026-03-09T12:00:00.000Z',
    objekte: [
      {
        id: 'o-5003',
        kundenId: 'k-1002',
        name: 'Retail Park Rosenheim',
        objektTyp: 'Einzelhandel',
        adresse: 'Salinstrasse 10, 83022 Rosenheim',
        region: 'Rosenheim',
        serviceIntervalDays: 60,
        riskClass: 'HIGH',
        status: 'PLANBAR',
      },
    ],
    ansprechpartner: [
      {
        id: 'c-9003',
        kundenId: 'k-1002',
        objektIds: ['o-5003'],
        name: 'Tom Berger',
        rolle: 'Einkauf',
        email: 't.berger@baukontor-rs.de',
        telefon: '+49 8031 889900',
        bevorzugterKanal: 'phone',
        dsgvoConsent: 'UNBEKANNT',
        status: 'NEU',
        primary: true,
      },
    ],
    reminders: [
      {
        id: 'r-7002',
        scope: 'ANSPRECHPARTNER',
        targetId: 'c-9003',
        title: 'Erstgespraech final bestaetigen',
        priority: 'CRITICAL',
        startAt: '2026-03-05T08:00:00.000Z',
        dueAt: '2026-03-11T18:00:00.000Z',
        pauseWindows: [],
        breachState: 'BREACHED',
      },
    ],
    activities: [
      {
        id: 'a-3002',
        entityType: 'KUNDE',
        entityId: 'k-1002',
        type: 'CONSENT_UPDATED',
        title: 'Consent offen',
        payload: 'Kein Opt-in fuer proaktive Kontaktaufnahme dokumentiert.',
        createdBy: 'System',
        createdAt: '2026-03-09T12:00:00.000Z',
        visibility: 'restricted',
      },
    ],
    duplicateCandidates: [
      {
        id: 'd-4001',
        leftEntityId: 'k-1002',
        rightEntityId: 'k-1003',
        score: 0.82,
        reasons: ['Name aehnlich', 'Gleiche Region', 'Kontakttelefon identisch'],
        resolution: 'OPEN',
      },
    ],
  },
  {
    id: 'k-1003',
    number: 'KND-2026-1003',
    name: 'Baukontor Rosenheim GmbH',
    branche: 'Gewerbe',
    segment: 'B',
    status: 'AKTIV',
    owner: 'Jan Klose',
    score: 70,
    consentState: 'ERTEILT',
    retentionClass: 'STANDARD',
    region: 'Rosenheim',
    createdAt: '2025-12-10T09:00:00.000Z',
    updatedAt: '2026-03-07T16:45:00.000Z',
    objekte: [],
    ansprechpartner: [
      {
        id: 'c-9004',
        kundenId: 'k-1003',
        objektIds: [],
        name: 'Thomas Berger',
        rolle: 'Einkauf',
        email: 'thomas.berger@baukontor-rs.de',
        telefon: '+49 8031 889900',
        bevorzugterKanal: 'email',
        dsgvoConsent: 'ERTEILT',
        status: 'VALIDIERT',
        primary: true,
      },
    ],
    reminders: [],
    activities: [],
    duplicateCandidates: [],
  },
];

function clone<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function getKundenRecords(): KundenRecord[] {
  return clone(kundenRecords);
}

export function getKundenRecordById(id: string): KundenRecord | undefined {
  const record = kundenRecords.find((entry) => entry.id === id);
  return record ? clone(record) : undefined;
}
