apiVersion: v1
kind: ConfigMap
metadata:
  name: zunftgewerk-config
  namespace: zunftgewerk
data:
  api-url: "https://api.zunftgewerk.de"
  landing-url: "https://zunftgewerk.de"
  web-url: "https://app.zunftgewerk.de"
  cors-allowed-origins: "https://zunftgewerk.de,https://app.zunftgewerk.de"
  passkey-rp-id: "app.zunftgewerk.de"
  passkey-origin: "https://app.zunftgewerk.de"
