apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zunftgewerk-ingress
  namespace: zunftgewerk
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zunftgewerk.de
        - app.zunftgewerk.de
        - api.zunftgewerk.de
      secretName: zunftgewerk-tls
  rules:
    - host: zunftgewerk.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zunftgewerk-landing
                port:
                  number: 3000
    - host: app.zunftgewerk.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zunftgewerk-web
                port:
                  number: 3001
    - host: api.zunftgewerk.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zunftgewerk-api
                port:
                  number: 8080
