apiVersion: v1
kind: Service
metadata:
  name: zunftgewerk-postgres
  namespace: zunftgewerk
spec:
  type: ClusterIP
  selector:
    app: zunftgewerk-postgres
  ports:
    - port: 5432
      targetPort: 5432
