import type { RuleProfile } from '@/lib/aufmass/overmeasure-types';

export const MALER_VOB_RULE_PROFILE: RuleProfile = {
  profileId: 'maler-vob-de-core',
  version: 1,
  legalReference: 'ATV DIN 18363 / VOB-konforme Übermessungslogik',
  fallbackPolicy: 'DEDUCT',
  rules: [
    {
      id: 'opening-under-2_5-overmeasure',
      scope: 'global',
      kind: 'OPENING',
      unit: 'm2',
      threshold: 2.5,
      decision: 'OVERMEASURE',
      priority: 100,
      rounding: 2,
      reasonTemplate: 'Öffnung <= 2.5 m² wird übermessen.',
    },
    {
      id: 'opening-over-2_5-deduct',
      scope: 'global',
      kind: 'OPENING',
      unit: 'm2',
      threshold: 2.5,
      decision: 'DEDUCT',
      priority: 90,
      rounding: 2,
      reasonTemplate: 'Öffnung > 2.5 m² wird abgezogen.',
    },
    {
      id: 'niche-under-2_5-overmeasure',
      scope: 'global',
      kind: 'NICHE',
      unit: 'm2',
      threshold: 2.5,
      decision: 'OVERMEASURE',
      priority: 80,
      rounding: 2,
      reasonTemplate: 'Nische <= 2.5 m² wird übermessen.',
    },
    {
      id: 'niche-over-2_5-deduct',
      scope: 'global',
      kind: 'NICHE',
      unit: 'm2',
      threshold: 2.5,
      decision: 'DEDUCT',
      priority: 70,
      rounding: 2,
      reasonTemplate: 'Nische > 2.5 m² wird abgezogen.',
    },
  ],
};
