export const dashboardUiTokens = {
  pageStack: 'space-y-[var(--dashboard-page-gap)]',
  sectionStack: 'space-y-[var(--dashboard-section-gap)]',
  contextRailStack: 'space-y-[var(--dashboard-section-gap)]',
  kpiGrid: 'grid gap-2 grid-cols-1 sm:grid-cols-2 md:grid-cols-4',
  mainGrid: 'grid items-start gap-[var(--dashboard-main-gap)] xl:grid-cols-[minmax(0,1.55fr)_minmax(320px,0.85fr)]',
  card: 'rounded-lg border border-border bg-white',
  cardHeader: 'px-4 py-3',
  cardBody: 'p-[var(--dashboard-card-padding)]',
  tableCell: 'px-4 py-3',
  heading: 'text-xl font-semibold tracking-tight leading-none',
  body: 'text-sm',
  meta: 'text-[11px] text-muted-foreground',
  kicker: 'text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground',
  kickerAccent: 'text-[10px] font-semibold uppercase tracking-[0.12em] text-foreground/70',
  iconShell: 'rounded-md border border-border/70 bg-muted/45 text-foreground/70',
  interactiveRing: 'focus-visible:ring-2 focus-visible:ring-primary/30 focus-visible:ring-offset-2',
  kpiValue: 'font-mono text-2xl font-bold tabular-nums leading-none tracking-tight',
  aufmassDensity: {
    panelGap: 'space-y-2.5',
    sectionGap: 'space-y-2',
    compactGridGap: 'gap-2',
    compactCardPadding: 'p-2.5',
    compactKicker: 'text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground',
  },
} as const;
