export const dashboardUiTokens = {
  pageStack: 'space-y-[var(--dashboard-page-gap)]',
  sectionStack: 'space-y-[var(--dashboard-section-gap)]',
  kpiGrid: 'grid gap-3 sm:grid-cols-2 lg:grid-cols-3',
  mainGrid: 'grid gap-[var(--dashboard-main-gap)] xl:grid-cols-[minmax(0,1.65fr)_minmax(320px,1fr)]',
  card: 'rounded-xl border border-border bg-sidebar/40',
  cardHeader: 'px-4 py-3',
  cardBody: 'p-[var(--dashboard-card-padding)]',
  tableCell: 'px-4 py-3',
  heading: 'text-xl font-semibold tracking-tight leading-none',
  body: 'text-sm',
  meta: 'text-[11px] text-muted-foreground',
  kicker: 'text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground',
  kickerAccent: 'text-[10px] font-semibold uppercase tracking-[0.12em] text-primary/85',
  iconShell: 'rounded-md border border-primary/25 bg-primary/10 text-primary',
  interactiveRing: 'focus-visible:ring-2 focus-visible:ring-primary/30 focus-visible:ring-offset-2',
  kpiValue: 'font-mono text-2xl font-bold tabular-nums leading-none tracking-tight',
} as const;
